version: "3.3"

services:
 server:
  build: server/
  command: python ./server.py
  ports:
   -9999:9999
 client:
  build: client/
  command: python ./client.py
  network_mode: host
  depends_on:
   - server